### PR TITLE
inviscriptions post

### PR DESCRIPTION
**Pull request by conduition**
https://github.com/bitcoin/bitcoin/pull/28408#issuecomment-1853422737

> I'd like to demonstrate why it is wildly impractical to even _detect_ arbitrary data push transactions, let alone filter them reliably. 
> 
> A subtle workaround to this PR:
> 
> 1. Encrypt the push-data/inscription
> 2. Format the ciphertext as hashes, pubkeys, and op-code sequences. 
> 3. Encode those hashes, pubkeys, etc into a valid-looking script pubkey.
> 4. Use that script pubkey as the inscription envelope.
> 5. Publish the decryption key _after_ the ciphertext is already included in a block.
> 6. Observers can identify, decode, and decrypt the inscription.
> 
> The witness script envelope containing the ciphertext is not analytically distinguishable from a normal bitcoin script, until the decryption key is revealed later. Maybe you could use heuristics, like "having too big of a witness" or "fulfilling a certain scripting pattern" to identify such inscriptions, but you're going to end up with lots of false positives/negatives, and there will always be other workarounds to bypass such heuristics.
> 
> https://conduition.io/bitcoin/inviscriptions/

### CODE REVIEW

**Comment by jangorecki** [comment]
I would find it useful if article mentions (link the issue in bitcoin GH repo that discusses that), as of today, probably the most "proper" way to address the problem, by using schnorr signature to encode inscriptions in a way that does not pollute block space. Censorship is not a solution. If there is no such issue in gh repo then I think it make sense to create one, so energy is not wasted on low-quality solution but rather figuring out (together BTC and ORDI community) proper solution.

**Comment by conduition** [comment]
@jangorecki I believe I did address this, [in the 'Critique' section](https://github.com/conduition/conduition.io/pull/5/files#diff-70ec328cf9c7e74bd32a313ee4a7ace98e5a29557095e33fb964049c52020025R54):

> I see this approach as pointless and inefficient for all its most common use cases.
>
> If the goal is to communicate and transfer ownership of a unique digital asset (a Non-Fungible Token), then one should instead defer to some authority or Oracle which certifies the unique ownership of that asset. That entity can publish an OpenTimestamped signature attesting to the ownership, or publish a signed transaction which includes a commitment to the new owner (e.g. using a Taproot-style commitment hash).
> 
> If the purpose of the inscription is to create a provenance anchor in time (e.g. to prove something existed before a certain time), then [OpenTimestamps](https://opentimestamps.org/) is a fast and zero-cost alternative - far simpler and with near zero on-chain footprint.

For those not aware, OpenTimestamps is effectively a commitment aggregation service which allows anyone to embed a proof-of-existence commitment into the blockchain for free. [See here for an explainer](https://bitcoin.stackexchange.com/questions/119718/how-does-opentimestamps-work-technically). The cost to the network is near zero.

Added some more text here to clarify in the conclusion.

**Comment by jangorecki** [comment]
Yes, what is missing is link to gh issue where such solution could be discussed

**Comment by conduition** [comment]
@jangorecki Bitcoin core already supports taproot commitments, and does not create inscriptions itself. The onus is now on the devs of apps/protocols which _do_ create inscriptions, to switch to more efficient off-chain solutions for data provenance.

**Comment by conduition** [comment]
Perhaps https://github.com/ordinals/ord might be the right place to mint such an issue?

**Comment by conduition** [comment]
https://github.com/ordinals/ord/discussions/2879

**Pull request merged**
